DEMO_CATEGORIES = [
    'Core vocabulary',
    'Communication',
    'Study and work',
    'Technology',
    'Academic skills',
]


DEMO_WORDS = [
    ('apple', 'яблоко', '[ˈæpəl]', 'I eat an apple every morning.', 'A1', 'noun', 'Core vocabulary'),
    ('house', 'дом', '[haʊs]', 'The house has a small garden.', 'A1', 'noun', 'Core vocabulary'),
    ('family', 'семья', '[ˈfæməli]', 'My family lives in this city.', 'A1', 'noun', 'Core vocabulary'),
    ('friend', 'друг', '[frend]', 'My friend helps me study English.', 'A1', 'noun', 'Communication'),
    ('school', 'школа', '[skuːl]', 'The school is near the park.', 'A1', 'noun', 'Study and work'),
    ('book', 'книга', '[bʊk]', 'This book is easy to read.', 'A1', 'noun', 'Study and work'),
    ('water', 'вода', '[ˈwɔːtə]', 'Water is important for health.', 'A1', 'noun', 'Core vocabulary'),
    ('city', 'город', '[ˈsɪti]', 'The city is large and busy.', 'A1', 'noun', 'Core vocabulary'),
    ('food', 'еда', '[fuːd]', 'The food is fresh.', 'A1', 'noun', 'Core vocabulary'),
    ('weather', 'погода', '[ˈweðə]', 'The weather is sunny today.', 'A1', 'noun', 'Core vocabulary'),
    ('morning', 'утро', '[ˈmɔːnɪŋ]', 'I study in the morning.', 'A1', 'noun', 'Core vocabulary'),
    ('lesson', 'урок', '[ˈlesən]', 'The lesson starts at nine.', 'A1', 'noun', 'Study and work'),
    ('habit', 'привычка', '[ˈhæbɪt]', 'Reading every day is a useful habit.', 'A2', 'noun', 'Core vocabulary'),
    ('journey', 'путешествие', '[ˈdʒɜːni]', 'The journey took three hours.', 'A2', 'noun', 'Core vocabulary'),
    ('choice', 'выбор', '[tʃɔɪs]', 'You have a choice between two options.', 'A2', 'noun', 'Communication'),
    ('schedule', 'расписание', '[ˈʃedjuːl]', 'I checked my schedule for tomorrow.', 'A2', 'noun', 'Study and work'),
    ('skill', 'навык', '[skɪl]', 'This course improves your speaking skill.', 'A2', 'noun', 'Study and work'),
    ('knowledge', 'знание', '[ˈnɒlɪdʒ]', 'Knowledge grows with practice.', 'A2', 'noun', 'Academic skills'),
    ('improve', 'улучшать', '[ɪmˈpruːv]', 'Practice helps improve vocabulary.', 'A2', 'verb', 'Study and work'),
    ('describe', 'описывать', '[dɪˈskraɪb]', 'Describe the picture in English.', 'A2', 'verb', 'Communication'),
    ('explain', 'объяснять', '[ɪkˈspleɪn]', 'Can you explain this rule?', 'A2', 'verb', 'Communication'),
    ('prepare', 'готовить', '[prɪˈpeə]', 'I prepare for the test every evening.', 'A2', 'verb', 'Study and work'),
    ('question', 'вопрос', '[ˈkwestʃən]', 'The question is simple.', 'A2', 'noun', 'Communication'),
    ('answer', 'ответ', '[ˈɑːnsə]', 'Write your answer in the form.', 'A2', 'noun', 'Communication'),
    ('achievement', 'достижение', '[əˈtʃiːvmənt]', 'Passing the exam was a great achievement.', 'B1', 'noun', 'Academic skills'),
    ('assignment', 'задание', '[əˈsaɪnmənt]', 'The teacher gave us a new assignment.', 'B1', 'noun', 'Study and work'),
    ('deadline', 'срок сдачи', '[ˈdedlaɪn]', 'The project deadline is next week.', 'B1', 'noun', 'Study and work'),
    ('requirement', 'требование', '[rɪˈkwaɪəmənt]', 'The application meets the main requirement.', 'B1', 'noun', 'Technology'),
    ('review', 'проверять', '[rɪˈvjuː]', 'Please review the report before sending it.', 'B1', 'verb', 'Study and work'),
    ('discussion', 'обсуждение', '[dɪˈskʌʃən]', 'The discussion helped us choose a solution.', 'B1', 'noun', 'Communication'),
    ('opportunity', 'возможность', '[ˌɒpəˈtjuːnəti]', 'This project is a good opportunity to learn.', 'B1', 'noun', 'Academic skills'),
    ('decision', 'решение', '[dɪˈsɪʒən]', 'The team made a decision.', 'B1', 'noun', 'Communication'),
    ('progress', 'прогресс', '[ˈprəʊɡres]', 'Your progress is visible in the dashboard.', 'B1', 'noun', 'Academic skills'),
    ('resource', 'ресурс', '[rɪˈsɔːs]', 'The website is a useful learning resource.', 'B1', 'noun', 'Technology'),
    ('responsibility', 'ответственность', '[rɪˌspɒnsəˈbɪləti]', 'Responsibility is important in teamwork.', 'B1', 'noun', 'Study and work'),
    ('confidence', 'уверенность', '[ˈkɒnfɪdəns]', 'Practice builds confidence.', 'B1', 'noun', 'Academic skills'),
    ('analysis', 'анализ', '[əˈnæləsɪs]', 'The analysis shows user progress.', 'B2', 'noun', 'Academic skills'),
    ('argument', 'аргумент', '[ˈɑːɡjəmənt]', 'A strong argument needs evidence.', 'B2', 'noun', 'Academic skills'),
    ('evidence', 'доказательство', '[ˈevɪdəns]', 'Evidence supports the conclusion.', 'B2', 'noun', 'Academic skills'),
    ('implementation', 'реализация', '[ˌɪmplɪmenˈteɪʃən]', 'The implementation uses Django views.', 'B2', 'noun', 'Technology'),
    ('integration', 'интеграция', '[ˌɪntɪˈɡreɪʃən]', 'Integration connects the interface and database.', 'B2', 'noun', 'Technology'),
    ('maintenance', 'сопровождение', '[ˈmeɪntənəns]', 'Maintenance keeps the project stable.', 'B2', 'noun', 'Technology'),
    ('performance', 'производительность', '[pəˈfɔːməns]', 'Performance affects user experience.', 'B2', 'noun', 'Technology'),
    ('reliability', 'надежность', '[rɪˌlaɪəˈbɪləti]', 'Reliability is important for web applications.', 'B2', 'noun', 'Technology'),
    ('strategy', 'стратегия', '[ˈstrætədʒi]', 'The strategy defines the learning path.', 'B2', 'noun', 'Academic skills'),
    ('evaluation', 'оценивание', '[ɪˌvæljuˈeɪʃən]', 'Evaluation helps measure the result.', 'B2', 'noun', 'Academic skills'),
    ('feedback', 'обратная связь', '[ˈfiːdbæk]', 'Feedback helps improve the answer.', 'B2', 'noun', 'Communication'),
    ('objective', 'цель', '[əbˈdʒektɪv]', 'The objective is clear and measurable.', 'B2', 'noun', 'Academic skills'),
    ('abstraction', 'абстракция', '[æbˈstrækʃən]', 'Abstraction simplifies complex logic.', 'C1', 'noun', 'Technology'),
    ('interoperability', 'совместимость систем', '[ˌɪntərɒpərəˈbɪləti]', 'Interoperability allows systems to exchange data.', 'C1', 'noun', 'Technology'),
    ('scalability', 'масштабируемость', '[ˌskeɪləˈbɪləti]', 'Scalability matters for growing services.', 'C1', 'noun', 'Technology'),
    ('optimization', 'оптимизация', '[ˌɒptɪmaɪˈzeɪʃən]', 'Optimization reduces unnecessary work.', 'C1', 'noun', 'Technology'),
    ('authentication', 'аутентификация', '[ɔːˌθentɪˈkeɪʃən]', 'Authentication confirms the user identity.', 'C1', 'noun', 'Technology'),
    ('authorization', 'авторизация', '[ˌɔːθəraɪˈzeɪʃən]', 'Authorization checks access rights.', 'C1', 'noun', 'Technology'),
    ('consistency', 'согласованность', '[kənˈsɪstənsi]', 'Consistency makes data predictable.', 'C1', 'noun', 'Technology'),
    ('methodology', 'методология', '[ˌmeθəˈdɒlədʒi]', 'The methodology describes the project approach.', 'C1', 'noun', 'Academic skills'),
    ('paradigm', 'парадигма', '[ˈpærədaɪm]', 'A paradigm shapes how developers solve problems.', 'C1', 'noun', 'Academic skills'),
    ('proficiency', 'владение языком', '[prəˈfɪʃənsi]', 'Language proficiency grows with practice.', 'C1', 'noun', 'Academic skills'),
    ('resilience', 'устойчивость', '[rɪˈzɪliəns]', 'Resilience helps a system recover from errors.', 'C1', 'noun', 'Technology'),
    ('taxonomy', 'классификация', '[tækˈsɒnəmi]', 'A taxonomy organizes vocabulary by levels.', 'C1', 'noun', 'Academic skills'),
    ('car', 'машина', '[kɑː]', 'The car is parked near the house.', 'A1', 'noun', 'Core vocabulary'),
    ('time', 'время', '[taɪm]', 'Time is important during the test.', 'A1', 'noun', 'Core vocabulary'),
    ('phone', 'телефон', '[fəʊn]', 'I use my phone to read new words.', 'A1', 'noun', 'Technology'),
    ('plan', 'план', '[plæn]', 'A good plan helps with learning.', 'A2', 'noun', 'Study and work'),
    ('message', 'сообщение', '[ˈmesɪdʒ]', 'I wrote a short message.', 'A2', 'noun', 'Communication'),
    ('result', 'результат', '[rɪˈzʌlt]', 'The result appears after the test.', 'A2', 'noun', 'Academic skills'),
    ('project', 'проект', '[ˈprɒdʒekt]', 'The project is ready for presentation.', 'B1', 'noun', 'Study and work'),
    ('meeting', 'встреча', '[ˈmiːtɪŋ]', 'The meeting starts after lunch.', 'B1', 'noun', 'Communication'),
    ('solution', 'решение проблемы', '[səˈluːʃən]', 'The team found a simple solution.', 'B1', 'noun', 'Study and work'),
    ('accessibility', 'доступность', '[əkˌsesəˈbɪləti]', 'Accessibility makes the interface easier to use.', 'B2', 'noun', 'Technology'),
    ('usability', 'удобство использования', '[ˌjuːzəˈbɪləti]', 'Usability is important for a learning website.', 'B2', 'noun', 'Technology'),
    ('validation', 'валидация', '[ˌvælɪˈdeɪʃən]', 'Validation checks the user input.', 'B2', 'noun', 'Technology'),
    ('deployment', 'развертывание', '[dɪˈplɔɪmənt]', 'Deployment prepares the application for users.', 'C1', 'noun', 'Technology'),
    ('modularity', 'модульность', '[ˌmɒdjuˈlærəti]', 'Modularity makes the code easier to maintain.', 'C1', 'noun', 'Technology'),
    ('persistence', 'сохранение данных', '[pəˈsɪstəns]', 'Persistence keeps data after the session ends.', 'C1', 'noun', 'Technology'),
]
