# Generated by Django 5.2.5 on 2026-05-25 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Всего вопросов')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Правильные ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=120, unique=True, verbose_name='Английское слово')),
                ('translation', models.CharField(max_length=180, verbose_name='Перевод')),
                ('transcription', models.CharField(blank=True, max_length=120, verbose_name='Транскрипция')),
                ('example', models.TextField(blank=True, verbose_name='Пример использования')),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced')], default='A1', max_length=2, verbose_name='Уровень')),
                ('part_of_speech', models.CharField(choices=[('noun', 'Существительное'), ('verb', 'Глагол'), ('adjective', 'Прилагательное'), ('adverb', 'Наречие'), ('phrase', 'Фраза'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Часть речи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['english'],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('learning', 'Изучается'), ('learned', 'Выучено')], default='learning', max_length=20, verbose_name='Статус')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильные ответы')),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name='Ошибки')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней тренировки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Слово пользователя',
                'verbose_name_plural': 'Слова пользователей',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=180, verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Попытка тренировки',
                'verbose_name_plural': 'Попытки тренировки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['english'], name='vocabulary__english_24e672_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['level'], name='vocabulary__level_b58920_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('user', 'word')},
        ),
    ]
